apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb-tomcat78-<BUILD_TAG>
spec:
  replicas: 2
  selector:
    app: myweb-tomcat78-<BUILD_TAG>
  template:
    metadata:
      labels:
        app: myweb-tomcat78-<BUILD_TAG>
    spec:
      containers:
      - image: 192.168.57.89:5000/centos-jdk8-tomcat7:v20180820
        name: myweb-tomcat78-<BUILD_TAG>
        resources:
          limits:
            cpu: "2"
            #memory: 4Gi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-essdk-svc
spec:
  ports:
  - name: tomcat-essdk
    port: 8080
    targetPort: 8080
    nodePort: 32222
  selector:
    app: tomcat-essdk
  type: NodePort
