apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myweb-tomcat78-<BUILD_TAG>
spec:
  serviceAccountName: jenkins
  replicas: 2
  template:
    metadata:
      labels:
        app: myweb-tomcat78-<BUILD_TAG>
    spec:
      containers:
      - image: 192.168.57.89:5000/myweb-tomcat78:<BUILD_TAG>
        name: myweb-tomcat78-<BUILD_TAG>
        resources:
          limits:
            cpu: "1"
            #memory: 4Gi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-tomcat78-svc-<BUILD_TAG>
spec:
  serviceAccountName: jenkins
  ports:
  - name: myweb-tomcat78
    port: 8080
    targetPort: 8080
  selector:
    app: myweb-tomcat78-<BUILD_TAG>
  type: NodePort
